{{- $tag := (gitHubLatestRelease "ast-grep/ast-grep").TagName | toString -}}
{{- $executableExtension := (replace "linux" "" (replace "darwin" "" (replace "windows" ".exe" .chezmoi.os))) -}}
{{- $astGrepArch := (replace "arm64" "aarch64" (replace "amd64" "x86_64" .chezmoi.arch)) -}}
{{- $astGrepOperatingSystem := (replace "linux" "unknown-linux-gnu" (replace "darwin" "apple-darwin" (replace "windows" "pc-windows-msvc" .chezmoi.os))) -}}

[ast-grep]
type = "archive-file"
url = {{ gitHubReleaseAssetURL "ast-grep/ast-grep" $tag (printf "app-%s-%s.zip" $astGrepArch $astGrepOperatingSystem) | quote }}
executable = true
targetPath = '{{ printf ".local/bin/ast-grep%s" $executableExtension }}'
path = '{{ printf "ast-grep%s" $executableExtension }}'

[sg]
type = "archive-file"
url = {{ gitHubReleaseAssetURL "ast-grep/ast-grep" $tag (printf "app-%s-%s.zip" $astGrepArch $astGrepOperatingSystem) | quote }}
executable = true
targetPath = '{{ printf ".local/bin/sg%s" $executableExtension }}'
path = '{{ printf "sg%s" $executableExtension }}'
