{{- $capitalizedOperatingSystemName := (replace "linux" "Linux" (replace "darwin" "Darwin" (replace "windows" "Windows" .chezmoi.os))) -}}
{{- $bufArch := (replace "amd64" "x86_64" .chezmoi.arch) -}}
{{- $tag := (gitHubLatestRelease "bufbuild/buf").TagName | toString -}}
{{- $executableExtension := (replace "linux" "" (replace "darwin" "" (replace "windows" ".exe" .chezmoi.os))) -}}
{{- $archiveExtension := (replace "linux" ".tar.gz" (replace "darwin" ".tar.gz" (replace "windows" ".zip" .chezmoi.os))) -}}
{{- $archiveUrl := (gitHubReleaseAssetURL "bufbuild/buf" $tag (printf "buf-%s-%s%s" $capitalizedOperatingSystemName $bufArch $archiveExtension)) -}}

[".local/bin/buf"]
type = "archive-file"
url = '{{ $archiveUrl }}'
path = '{{ printf "buf/bin/buf%s" $executableExtension }}'
executable = true
targetPath = '{{ printf ".local/bin/buf%s" $executableExtension }}'

[".local/bin/protoc-gen-buf-breaking"]
type = "archive-file"
url = '{{ $archiveUrl }}'
path = '{{ printf "buf/bin/protoc-gen-buf-breaking%s" $executableExtension }}'
executable = true
targetPath = '{{ printf ".local/bin/protoc-gen-buf-breaking%s" $executableExtension }}'

[".local/bin/protoc-gen-buf-lint"]
type = "archive-file"
url = '{{ $archiveUrl }}'
path = '{{ printf "buf/bin/protoc-gen-buf-lint%s" $executableExtension }}'
executable = true
targetPath = '{{ printf ".local/bin/protoc-gen-buf-lint%s" $executableExtension }}'

{{ if ne .chezmoi.os "windows" -}}

[".local/share/zsh/site-functions/_buf"]
type = "archive-file"
url = '{{ $archiveUrl }}'
path = 'buf/share/zsh/site-functions/_buf'
executable = false

[".local/share/man/man1"]
type = "archive"
url = '{{ $archiveUrl }}'
include = ["**/*.1"]
stripComponents = 4
executable = false

{{- end }}
