{{- $tag := (gitHubLatestRelease "colbymchenry/codegraph").TagName | toString -}}

[".codegraph/versions/current"]
{{ if ne .chezmoi.os "windows" }}
targetPath = '{{ printf ".codegraph/versions/%s" $tag }}'
{{ else }}
targetPath = '{{ joinPath (env "LOCALAPPDATA") "codegraph" "current" }}'
{{ end }}
type = "archive"
url = '{{ gitHubReleaseAssetURL "colbymchenry/codegraph" $tag (printf "codegraph-%s-%s.tar.gz" (replace "windows" "win32" .chezmoi.os) (replace "amd64" "x64" .chezmoi.arch)) }}'
stripComponents = 1
refreshPeriod = "672h"
