{{- $arch := (replace "amd64" "x86_64" (replace "arm64" "aarch64" .chezmoi.arch)) -}}

{{- $tag := ((gitHubLatestRelease "openai/codex").TagName | toString) -}}
{{- $release := (replace "rust-v" "" $tag) -}}
{{- $target := (replace "linux" "unknown-linux-musl" (replace "darwin" "apple-darwin" (replace "windows" "pc-windows-msvc" .chezmoi.os))) -}}

{{- $releasePath := (printf "%s-%s-%s" $release $arch $target) -}}
{{- $asset := (printf "codex-package-%s-%s.tar.zst" $arch $target) -}}

{{- $installationPath := (joinPath ".codex" "packages" "standalone" "releases" $releasePath) -}}

[codex]
type = "archive"
url = '{{ gitHubReleaseAssetURL "openai/codex" $tag $asset }}'
stripComponents = 0
targetPath = '{{ $installationPath }}'
