{{- $tag := (gitHubLatestRelease "docker/docker-credential-helpers").TagName | toString -}}

{{- if eq .chezmoi.os "linux" }}

[".local/bin/docker-credential-secretservice"]
type = "file"
url = {{ gitHubReleaseAssetURL "docker/docker-credential-helpers" $tag (printf "docker-credential-secretservice-%s.%s-%s" $tag .chezmoi.os .chezmoi.arch) | quote }}
executable = true

{{- else if eq .chezmoi.os "darwin" }}

[".local/bin/docker-credential-osxkeychain"]
type = "file"
url = {{ gitHubReleaseAssetURL "docker/docker-credential-helpers" $tag (printf "docker-credential-osxkeychain-%s.%s-%s" $tag .chezmoi.os .chezmoi.arch) | quote }}
executable = true

{{- else if eq .chezmoi.os "windows" }}

[".local/bin/docker-credential-wincred.exe"]
type = "file"
url = {{ gitHubReleaseAssetURL "docker/docker-credential-helpers" $tag (printf "docker-credential-wincred-%s.%s-%s.exe" $tag .chezmoi.os .chezmoi.arch) | quote }}
executable = true

{{- end }}