{{- $tag := (gitHubLatestRelease "docker/docker-credential-helpers").TagName | toString -}}

{{- if eq .chezmoi.os "linux" }}

[docker-credential-secretservice]
type = "file"
targetPath = '.local/bin/docker-credential-secretservice'
url = {{ gitHubReleaseAssetURL "docker/docker-credential-helpers" $tag (printf "docker-credential-secretservice-%s.%s-%s" $tag .chezmoi.os .chezmoi.arch) | quote }}
executable = true

{{- else if eq .chezmoi.os "darwin" }}

[docker-credential-osxkeychain]
type = "file"
targetPath = '.local/bin/docker-credential-osxkeychain'
url = {{ gitHubReleaseAssetURL "docker/docker-credential-helpers" $tag (printf "docker-credential-osxkeychain-%s.%s-%s" $tag .chezmoi.os .chezmoi.arch) | quote }}
executable = true

{{- else if eq .chezmoi.os "windows" }}

[docker-credential-wincred]
type = "file"
targetPath = '.local/bin/docker-credential-wincred.exe'
url = {{ gitHubReleaseAssetURL "docker/docker-credential-helpers" $tag (printf "docker-credential-wincred-%s.%s-%s.exe" $tag .chezmoi.os .chezmoi.arch) | quote }}
executable = true

{{- end }}