{{- $tag := (gitHubLatestRelease "garden-rs/garden").TagName | toString -}}
{{- $version := trimPrefix "v" $tag -}}
{{- $archiveExtension := (replace "linux" ".tar.gz" (replace "darwin" ".tar.gz" (replace "windows" ".zip" .chezmoi.os))) -}}
{{- $executableExtension := (replace "linux" "" (replace "darwin" "" (replace "windows" ".exe" .chezmoi.os))) -}}
{{- $gardenArch := (replace "arm64" "aarch64" (replace "amd64" "x86_64" .chezmoi.arch)) -}}
{{- $gardenOperatingSystem := (replace "linux" "unknown-linux-gnu" (replace "darwin" "apple-darwin" (replace "windows" "pc-windows-msvc" .chezmoi.os))) -}}
{{- $stem := (printf "garden-%s-%s-%s" $version $gardenArch $gardenOperatingSystem) -}}

[garden]
type = "archive-file"
url = {{ gitHubReleaseAssetURL "garden-rs/garden" $tag (printf "%s%s" $stem $archiveExtension) | quote }}
executable = true
targetPath = '{{ printf ".local/bin/garden%s" $executableExtension }}'
path = '{{ printf "%s/garden%s" $stem $executableExtension }}'
