{{- $latestReleaseUrl := (getRedirectedURL "https://gitlab.com/api/v4/projects/34675721/releases/permalink/latest") -}}
{{- $latestRelease := output "curl" "-fsSL" $latestReleaseUrl | fromJson -}}

{{- $archiveExtension := (replace "linux" ".tar.gz" (replace "darwin" ".tar.gz" (replace "windows" ".zip" .chezmoi.os))) -}}
{{- $executableExtension := (replace "linux" "" (replace "darwin" "" (replace "windows" ".exe" .chezmoi.os))) -}}

{{- $archiveUrl := (printf "https://gitlab.com/gitlab-org/cli/-/releases/%s/downloads/glab_%s_%s_%s%s" $latestRelease.tag_name (replace "v" "" $latestRelease.tag_name) .chezmoi.os .chezmoi.arch $archiveExtension) -}}
{{- $glabSkillUrl := (printf "https://gitlab.com/gitlab-org/cli/-/raw/%s/internal/commands/skills/bundled/assets/glab/SKILL.md?ref_type=tags" $latestRelease.tag_name) -}}
{{- $glabStackSkillUrl := (printf "https://gitlab.com/gitlab-org/cli/-/raw/%s/internal/commands/skills/bundled/assets/glab-stack/SKILL.md?ref_type=tags" $latestRelease.tag_name) -}}

[glab]
targetPath = '{{ printf ".local/bin/glab%s" $executableExtension }}'
type = "archive-file"
url = '{{ $archiveUrl }}'
path = '{{ printf "bin/glab%s" $executableExtension }}'
executable = true

[glab-skill]
type = "file"
targetPath = '.agents/skills/glab/SKILL.md'
url = '{{ $glabSkillUrl }}'

[glab-stack-skill]
type = "file"
targetPath = '.agents/skills/glab-stack/SKILL.md'
url = '{{ $glabStackSkillUrl }}'

