{{- $archiveExtension := (replace "linux" ".tar.gz" (replace "darwin" ".tar.gz" (replace "windows" ".zip" .chezmoi.os))) -}}
{{- $executableExtension := (replace "linux" "" (replace "darwin" "" (replace "windows" ".exe" .chezmoi.os))) -}}

{{- $tag := (gitHubLatestRelease "helm/helm").TagName | toString -}}

[".local/bin/helm"]
targetPath = '{{ printf ".local/bin/helm%s" $executableExtension }}'
type = "archive-file"
url = '{{ printf "https://get.helm.sh/helm-%s-%s-%s%s" $tag .chezmoi.os .chezmoi.arch $archiveExtension }}'
path = '{{ printf "%s-%s/helm" .chezmoi.os .chezmoi.arch }}'
executable = true