{{- $tag := (gitHubLatestRelease "artempyanykh/marksman").TagName | toString -}}

{{- if eq .chezmoi.os "linux" }}

[marksman]
type = "file"
targetPath = '.local/bin/marksman'
url = {{ gitHubReleaseAssetURL "artempyanykh/marksman" $tag (printf "marksman-%s-%s" .chezmoi.os (replace "amd64" "x64" .chezmoi.arch)) | quote }}
executable = true

{{- else if eq .chezmoi.os "darwin" }}

[marksman]
type = "file"
targetPath = '.local/bin/marksman'
url = {{ gitHubReleaseAssetURL "artempyanykh/marksman" $tag "marksman-macos" | quote }}
executable = true

{{- else if eq .chezmoi.os "windows" }}

[marksman]
type = "file"
targetPath = '.local/bin/marksman.exe'
url = {{ gitHubReleaseAssetURL "artempyanykh/marksman" $tag "marksman.exe" | quote }}
executable = true

{{- end }}