{{- if or (eq .chezmoi.os "linux") (eq .chezmoi.os "darwin") }}

[".local/bin/minikube"]
type = "archive-file"
url = '{{ gitHubLatestReleaseAssetURL "kubernetes/minikube" (printf "minikube-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) }}'
path = '{{ printf "out/minikube-%s-%s" .chezmoi.os .chezmoi.arch }}'
executable = true

{{- else if eq .chezmoi.os "windows" }}

[".local/bin/minikube.exe"]
type = "archive-file"
url = '{{ gitHubLatestReleaseAssetURL "kubernetes/minikube" (printf "minikube-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) }}'
path = '{{ printf "out/minikube-%s-%s.exe" .chezmoi.os .chezmoi.arch }}'
executable = true

{{- end }}