{{- if ne .chezmoi.os "windows" }}

[prezto]
type = "git-repo"
targetPath = ".config/zsh/.zprezto"
url = "https://github.com/sorin-ionescu/prezto.git"
clone.args = ["--recursive"]
refreshPeriod = "8760h"

{{- end }}
