[".local/bin/wakatime-cli"]
type = "archive-file"
url = '{{ gitHubLatestReleaseAssetURL "wakatime/wakatime-cli" (printf "wakatime-cli-%s-%s.zip" .chezmoi.os .chezmoi.arch) }}'
executable = true
path = '{{ printf "wakatime-cli-%s-%s" .chezmoi.os .chezmoi.arch }}'
refreshPeriod = "672h"
