{{- $executableExtension := (replace "linux" "" (replace "darwin" "" (replace "windows" ".exe" .chezmoi.os))) -}}

[wakatime-cli]
type = "archive-file"
targetPath = '{{ printf ".local/bin/wakatime-cli%s" $executableExtension }}'
url = '{{ gitHubLatestReleaseAssetURL "wakatime/wakatime-cli" (printf "wakatime-cli-%s-%s.zip" .chezmoi.os .chezmoi.arch) }}'
executable = true
path = '{{ printf "wakatime-cli-%s-%s%s" .chezmoi.os .chezmoi.arch $executableExtension }}'
