[tools]
bun = "latest"
"cargo:git-trim" = "latest"
deno = "latest"
go = "latest"
java = "zulu-23"
node = "latest"
"pipx:mcp-server-git" = "latest"
python = "latest"
ruby = "3.4"
rust = "latest"
uv = "latest"
yarn = "latest"
