[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = ["zulu-17", "zulu-24"]
node = "24"
yarn = "latest"
python = "latest"
uv = "latest"
"pipx:mcp-server-git" = "latest"
rust = "latest"
"cargo:git-trim" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:mcp-remote" = "latest"
"npm:task-master-ai" = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
