#!/usr/bin/env bash
# shellcheck disable=SC2016
# (printf format strings contain literal markdown backticks and a literal
# $schema JSON Schema key; single quotes are intentional and required.)
#
# archinstall/inspect-hardware.sh
#
# Hardware inventory reporter for the running machine. Prints a Markdown
# report mapping detected hardware to archinstall config decisions.
#
# Used by the `archinstall-host` skill (.opencode/skills/archinstall-host/)
# during Phase 2 (gather hardware facts) when the target host matches the
# current machine.
#
# Usage:
#   archinstall/inspect-hardware.sh                # print report to stdout
#   archinstall/inspect-hardware.sh -o report.md   # write to file
#   sudo archinstall/inspect-hardware.sh -o ...    # include dmidecode output
#
# Most checks work without root. dmidecode (system / bios / chassis) and a
# few sbctl/bootctl status fields require root for full output; the script
# notes when output is degraded by missing privileges.
#
# Single-platform (Linux) by design — see AGENTS.md script-parity exception.
# Distro-portable: this is NOT Arch-specific; pacman-only checks no-op when
# the tool is missing. Useful from any Linux host you want to provision.

set -euo pipefail

OUTPUT="-"

usage() {
  cat <<USAGE
Usage: archinstall/inspect-hardware.sh [-o OUTPUT]

  -o, --output PATH   Write report to PATH (default: stdout)
  -h, --help          Show this help

Run with sudo for full DMI / BIOS / chassis output (otherwise those
sections show "needs root").
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output) OUTPUT="${2:?missing PATH for -o}"; shift 2 ;;
    -h|--help)   usage; exit 0 ;;
    *)           printf 'inspect-hardware: unknown arg: %s\n' "$1" >&2; usage >&2; exit 64 ;;
  esac
done

# ----- helpers ---------------------------------------------------------------

# section_cmd <heading> <command...>
# Run <command...>; emit "### heading" then a fenced code block with output.
# Captures stderr and exit status so missing tools don't abort the script.
section_cmd() {
  local heading="$1"; shift
  printf '\n### %s\n\n```\n' "$heading"
  if "$@" 2>&1; then
    :
  else
    printf '\n(exit %d — tool unavailable, missing privileges, or no devices)\n' "$?"
  fi
  printf '```\n'
}

have() { command -v "$1" >/dev/null 2>&1; }

# tool_or_skip <heading> <tool> <command...>
# Like section_cmd but skips entirely (with a note) when <tool> isn't on PATH.
tool_or_skip() {
  local heading="$1" tool="$2"
  shift 2
  if have "$tool"; then
    section_cmd "$heading" "$@"
  else
    printf '\n### %s\n\n```\n(skipped: %s not installed)\n```\n' "$heading" "$tool"
  fi
}

# ----- report ----------------------------------------------------------------

emit_report() {
  printf '# Hardware inventory: %s\n\n' "$(hostname 2>/dev/null || printf 'unknown-host')"
  printf 'Generated: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'Generated by: archinstall/inspect-hardware.sh\n'
  printf '\nThis report is consumed by the [`archinstall-host`](../.opencode/skills/archinstall-host/SKILL.md) skill.\n'
  printf 'Use the "archinstall config decisions" table at the bottom to fill in `user_configuration.json`.\n'

  printf '\n## 1. System identity\n'
  section_cmd 'hostnamectl' hostnamectl
  section_cmd '/etc/os-release' cat /etc/os-release
  section_cmd 'uname -a' uname -a

  printf '\n## 2. CPU\n'
  section_cmd 'lscpu' lscpu
  printf '\nVendor ID drives the microcode package: `GenuineIntel` → `intel-ucode`, `AuthenticAMD` → `amd-ucode`.\n'

  printf '\n## 3. Memory\n'
  section_cmd 'free -h' free -h
  tool_or_skip 'lsmem' lsmem lsmem

  printf '\n## 4. PCI devices (with kernel drivers)\n'
  section_cmd 'lspci -nnk' lspci -nnk
  printf '\nLook for: VGA/3D/Display (GPU vendor → `gfx_driver`), Network controller (wired NIC), Network controller (Wi-Fi), Audio device, NVMe controller.\n'

  printf '\n## 5. USB devices\n'
  section_cmd 'lsusb -tv' lsusb -tv
  printf '\nLook for: Bluetooth dongle (often integrated, vendor 8087=Intel), fingerprint reader (vendor 06cb=Synaptics, 138a=Validity, 27c6=Goodix), webcam, dock components, mobile broadband modem.\n'

  printf '\n## 6. Loaded kernel modules\n'
  section_cmd 'lsmod (top 60 by usage)' sh -c 'lsmod | head -60'
  printf '\nProxy for what hardware is currently driven. Look for: i915/xe (Intel GPU), amdgpu (AMD GPU), nvidia/nouveau, iwlwifi (Intel Wi-Fi), btusb (Bluetooth), snd_sof (Intel SOF audio), nvme.\n'

  printf '\n## 7. Block devices\n'
  section_cmd 'lsblk -f' lsblk -f -o NAME,FSTYPE,LABEL,UUID,MOUNTPOINTS,SIZE,TYPE
  printf '\nCurrent partition layout. `crypto_LUKS` rows = existing LUKS volumes — informs `disk_config.disk_encryption`.\n'

  printf '\n## 8. Boot environment\n'
  section_cmd '/proc/cmdline' cat /proc/cmdline
  tool_or_skip 'bootctl status' bootctl bootctl status
  tool_or_skip 'sbctl status' sbctl sbctl status
  tool_or_skip 'efibootmgr' efibootmgr efibootmgr -v
  printf '\nIf Secure Boot is already on AND keys are user-enrolled, the new host can re-use the same `bootloader_config = { Systemd-boot, uki: true }` shape.\n'

  printf '\n## 9. TPM\n'
  section_cmd '/sys/class/tpm/' ls -la /sys/class/tpm/
  section_cmd 'TPM version' sh -c 'cat /sys/class/tpm/tpm0/tpm_version_major 2>/dev/null || printf "no tpm0 device\n"'
  tool_or_skip 'systemd-cryptenroll --tpm2-device=list' systemd-cryptenroll systemd-cryptenroll --tpm2-device=list
  tool_or_skip 'systemd-analyze has-tpm2' systemd-analyze systemd-analyze has-tpm2
  printf '\nIf TPM 2.0 is present (and a LUKS root exists), the host should run a first-boot `secureboot-tpm-enroll.service` to bind TPM2 unlock to PCR 7. Model on `archinstall/UX5606/`.\n'

  printf '\n## 10. DMI / SMBIOS (root recommended)\n'
  section_cmd 'dmidecode -t system' sh -c 'dmidecode -t system 2>&1 || printf "needs root for full output\n"'
  section_cmd 'dmidecode -t bios' sh -c 'dmidecode -t bios 2>&1 || printf "needs root for full output\n"'
  section_cmd 'dmidecode -t chassis' sh -c 'dmidecode -t chassis 2>&1 || printf "needs root for full output\n"'
  printf '\nManufacturer + product name → ArchWiki model page lookup. Chassis type "Notebook" → laptop-specific packages.\n'

  printf '\n## 11. Network stack\n'
  section_cmd 'ip -br link' ip -br link
  section_cmd 'ip -br addr' ip -br addr
  tool_or_skip 'NetworkManager devices' nmcli nmcli device
  tool_or_skip 'iwd devices' iwctl iwctl device list
  printf '\nIf NetworkManager already manages the relevant interfaces, set `network_config.type = "nm"`. Set `iwd` only if explicitly preferred.\n'

  printf '\n## 12. Audio\n'
  section_cmd '/proc/asound/cards' cat /proc/asound/cards
  tool_or_skip 'aplay -l' aplay aplay -l
  printf '\nLook for "Intel SOF" / `snd_sof` modules → REQUIRES `sof-firmware` package on Arch (no sound otherwise on T14 Gen 2 / Tiger Lake / Alder Lake / Meteor Lake).\n'

  printf '\n## 13. Bluetooth\n'
  section_cmd 'rfkill list bluetooth' sh -c 'rfkill list bluetooth 2>&1 || printf "rfkill not available\n"'
  tool_or_skip 'bluetoothctl list' bluetoothctl bluetoothctl list

  printf '\n## 14. Firmware updates (fwupd)\n'
  tool_or_skip 'fwupdmgr get-devices' fwupdmgr fwupdmgr get-devices

  printf '\n## 15. DMI fingerprint (for `host-metadata.json` auto-detect)\n\n'
  printf '```\n'
  local field val
  for field in sys_vendor product_name product_version chassis_type bios_vendor bios_version board_vendor board_name; do
    val="$(cat "/sys/class/dmi/id/$field" 2>/dev/null || printf '(not readable)')"
    printf '%-18s = %s\n' "$field" "$val"
  done
  printf '```\n\n'
  printf 'Use this fingerprint to write `archinstall/<hostname>/host-metadata.json` so\n'
  printf '`archinstall/test-host.sh` can auto-detect the host on this machine:\n\n'
  printf '```json\n'
  printf '{\n'
  printf '  "$schema": "host-metadata.v1",\n'
  printf '  "hostname": "<hostname>",\n'
  printf '  "description": "<vendor + model>",\n'
  printf '  "archwiki_page": "https://wiki.archlinux.org/title/...",\n'
  printf '  "dmi_match": {\n'
  printf '    "sys_vendor":      %s,\n' "$(printf '"%s"' "$(cat /sys/class/dmi/id/sys_vendor 2>/dev/null || printf '<exact or glob>')")"
  printf '    "product_name":    %s,\n' "$(printf '"%s"' "$(cat /sys/class/dmi/id/product_name 2>/dev/null || printf '<exact or glob>')")"
  printf '    "product_version": %s\n'  "$(printf '"%s"' "$(cat /sys/class/dmi/id/product_version 2>/dev/null || printf '<exact or glob>')")"
  printf '  }\n'
  printf '}\n'
  printf '```\n\n'
  printf 'Glob patterns supported (`*`, `?`). Empty / missing fields are wildcards.\n'

  printf '\n---\n\n'
  printf '## archinstall config decisions (apply to `user_configuration.json`)\n\n'
  printf '| Section finding | `user_configuration.json` knob | Value |\n'
  printf '|---|---|---|\n'
  printf '| CPU vendor (lscpu) | `packages[]` | add `intel-ucode` (Intel) or `amd-ucode` (AMD) |\n'
  printf '| GPU vendor (lspci VGA/3D) | `profile_config.gfx_driver` | `Intel (open-source)` / `AMD / ATI (open-source)` / `Nvidia open-kernel` / `Nouveau` |\n'
  printf '| GPU vendor | `packages[]` | Intel: `mesa vulkan-intel intel-media-driver libva-intel-driver`; AMD: `mesa vulkan-radeon lib32-vulkan-radeon`; NVIDIA open: `nvidia-open-dkms libva-nvidia-driver` |\n'
  printf '| Audio Intel SOF in lsmod | `packages[]` | add `sof-firmware` (REQUIRED on Tiger Lake+ for sound) |\n'
  printf '| Wi-Fi present (lspci Network 802.11) | `network_config.type` | `nm` (NetworkManager — default) |\n'
  printf '| Bluetooth present | `app_config.bluetooth_config.enabled` | `true` |\n'
  printf '| Chassis = Notebook (hostnamectl) | `app_config.power_management_config.power_management` | `power-profiles-daemon` |\n'
  printf '| Chassis = Notebook | `packages[]` | add `brightnessctl` (and `fprintd` if fingerprint reader detected) |\n'
  printf '| LUKS root visible (lsblk crypto_LUKS) | `disk_config.disk_encryption.encryption_type` | `luks` |\n'
  printf '| TPM 2.0 present | first-boot service | install host-specific `secureboot-tpm-enroll.service` per UX5606 pattern |\n'
  printf '| Secure Boot supported (bootctl) | `bootloader_config` | `{ "bootloader": "Systemd-boot", "uki": true, "removable": false }` |\n'
  printf '| fwupdmgr lists device | `services[]` | add `fwupd-refresh.timer` (or run manually) |\n'

  printf '\n## Next step\n\n'
  printf 'Cross-reference this report with the ArchWiki page for your laptop/desktop model:\n'
  printf '  https://wiki.archlinux.org/title/Special:Search?search=%%22%s%%22\n' "$(hostnamectl --static 2>/dev/null || hostname)"
  printf '\nThen run `archinstall --dry-run` on the target machine, walk the TUI, and copy `/var/log/archinstall/user_configuration.json` into `archinstall/<hostname>/`.\n'
}

if [[ "$OUTPUT" == "-" ]]; then
  emit_report
else
  emit_report > "$OUTPUT"
  printf 'inspect-hardware: wrote report to %s\n' "$OUTPUT"
fi
