[tools]
"github:wakatime/wakatime-cli" = { version = "latest", rename_exe = ' "wakatime-cli.exe" } }', platforms = '{ linux-x64 = { asset_pattern = "wakatime-cli-linux-amd64.zip" }', linux-arm64 = ' { asset_pattern = "wakatime-cli-linux-arm64.zip" }', macos-arm64 = ' { asset_pattern = "wakatime-cli-darwin-arm64.zip" }', windows-x64 = ' { asset_pattern = "wakatime-cli-windows-amd64.zip"', windows-arm64 = ' { asset_pattern = "wakatime-cli-windows-arm64.zip"', asset_pattern = "wakatime-cli-*-*.zip" }
node = "latest"
python = "3.14"
