[tools]
aube = "latest"
bun = "latest"
"npm:@colbymchenry/codegraph" = "latest"
"npm:@sentry/dotagents" = "latest"
rust = { version = "latest", components = "rust-analyzer,rust-src" }

[hooks]
postinstall = [
  { run = "bash -c \"cd packages; vp install\"" },
  { run = "bash -c \"cd crates/mxm4-haptic; cargo fetch\"" },
  { run = "dotagents --project install" },
  { run = "codegraph init" },
  { run = "codegraph sync" },
]

[settings]
lockfile = true
