# Environment variables
. "/nix/store/cmnk2wc0wyxw37p18q8wsgzzs7axdpfm-hm-session-vars.sh/etc/profile.d/hm-session-vars.sh"

# Only source this once
if [[ -z "$__HM_ZSH_SESS_VARS_SOURCED" ]]; then
  export __HM_ZSH_SESS_VARS_SOURCED=1
  
fi

# Generated by Nix
source /nix/store/d3m4ppwxkf8ql7zglrwdmw3mx1s8zzjd-zsh-prezto-0-unstable-2025-07-30/share/zsh-prezto/runcoms/zshenv
