[tools]
bun = "latest"
go = "latest"
node = "latest"
yarn = "latest"
rust = { version = "latest", components = "rust-analyzer,rust-src" }
usage = "latest"
uv = "latest"
"cargo:git-trim" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@bufbuild/buf" = "latest"
pipx = { version = "latest", os = ["linux", "macos"] }
"npm:@electron/asar" = "latest"
"github:rust-lang/rust-analyzer" = "latest"
"npm:typescript-language-server" = "latest"
ruby = [
  { version = "latest", os = [
    "linux",
    "macos",
  ] },
  { version = "3.4", os = [
    "linux",
    "macos",
  ] },
  { version = "3.2", os = [
    "linux",
    "macos",
  ] },
]
"npm:npm" = "latest"
"npm:shadcn" = "latest"
ast-grep = "latest"
"npm:tokscale" = "latest"
"npm:sharp-cli" = "latest"
"npm:portless" = "latest"
glab = { version = "latest", exe = "glab" }
"npm:node-gyp" = "latest"
shellcheck = "latest"
"npm:bash-language-server" = "latest"
marksman = "latest"

# agentic ai
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
claude-code = "latest"

# opencode for Windows
"npm:opencode-ai" = { version = "latest", os = ["windows"] }

[tools."github:wakatime/wakatime-cli"]
version = "latest"
rename_exe = "wakatime-cli"
os = ["linux", "macos"]

[tools."github:wakatime/wakatime-cli".platforms]
linux-x64 = { asset_pattern = "wakatime-cli-linux-amd64.zip" }
linux-arm64 = { asset_pattern = "wakatime-cli-linux-arm64.zip" }
macos-arm64 = { asset_pattern = "wakatime-cli-darwin-arm64.zip" }
macos-x64 = { asset_pattern = "wakatime-cli-darwin-amd64.zip" }

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
all_compile = false

[settings.ruby]
compile = false

[env]
OPENCODE_DISABLE_DEFAULT_PLUGINS = 1
OPENCODE_EXPERIMENTAL_WORKSPACES = 1
OPENCODE_DISABLE_CLAUDE_CODE = 1
OPENCODE_DISABLE_CLAUDE_CODE_PROMPT = 1
OPENCODE_DISABLE_CLAUDE_CODE_SKILLS = 1
