[tools]
# Core runtimes and package managers
aube = "latest"
bun = "latest"
go = "latest"
node = "latest"
python = "latest"
ruby = [
  { version = "latest", os = [
    "linux",
    "macos",
  ] },
  { version = "3.4", os = [
    "linux",
    "macos",
  ] },
]
rust = { version = "latest", components = "rust-analyzer,rust-src" }
uv = "latest"
yarn = "latest"

# Standalone CLIs and language tooling
ast-grep = "latest"
"cargo:git-trim" = "latest"
"cargo:kdotool" = { version = "latest", os = ["linux"] }
glab = { version = "latest", exe = "glab" }
gh = "latest"
"github:rust-lang/rust-analyzer" = "latest"
pipx = { version = "latest", os = ["linux", "macos"], depends = ["python"] }
shellcheck = "latest"
usage = "latest"
viteplus = "latest"
"aqua:wasm-bindgen/wasm-pack" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@electron/asar" = "latest"
"npm:@playwright/cli" = "latest"
"npm:bash-language-server" = "latest"
"npm:node-gyp" = "latest"
"npm:npm" = "latest"
"npm:portless" = "latest"
"npm:shadcn" = "latest"
"npm:sharp-cli" = "latest"
"npm:tokscale" = "latest"
"npm:typescript-language-server" = "latest"
"npm:wrangler" = "latest"
"npm:yaml-language-server" = "latest"
"npm:cypress" = { version = "latest", allow_builds = ["cypress"] }
"pipx:mmdc" = "latest"

# Agentic AI
claude-code = "latest"
"npm:@sentry/dotagents" = "latest"
"npm:@openai/codex" = "latest"
"npm:@moonshot-ai/kimi-code" = { version = "latest", allow_builds = [
  "@moonshot-ai/kimi-code",
  "node-pty",
] }
"github:njbrake/agent-of-empires" = { version = "latest", rename_exe = "aoe", os = [
  "linux",
  "macos",
] }
antigravity-cli = "latest"
"npm:@z_ai/mcp-server" = "latest"

[settings]
all_compile = false
experimental = true
idiomatic_version_file_enable_tools = []
minimum_release_age = "24h"
minimum_release_age_excludes = [
  "gh",
  "glab",
  "claude-code",
  "pipx",
  "npm:@moonshot-ai/kimi-code",
  "npm:@openai/codex",
  "npm:npm",
  "npm:tokscale",
  "github:njbrake/agent-of-empires",
  "github:anomalyco/opencode",
  "github:wakatime/wakatime-cli",
]
lockfile = true
locked = false

[settings.github]
use_git_credentials = true

[settings.ruby]
compile = false

[settings.python]
compile = false

[settings.npm]
package_manager = "aube"

[env]
OPENCODE_DISABLE_CLAUDE_CODE = 1
OPENCODE_DISABLE_CLAUDE_CODE_PROMPT = 1
OPENCODE_DISABLE_CLAUDE_CODE_SKILLS = 1
OPENCODE_EXPERIMENTAL_WEBSOCKETS = 1
OPENCODE_EXPERIMENTAL_WORKSPACES = 1
OMO_SEND_ANONYMOUS_TELEMETRY = 0
OMO_CODEX_SEND_ANONYMOUS_TELEMETRY = 0
